server:
  port: 8011    
 
spring:    
  application:
    name: product-service   
     
management:
  security:
    enabled: false  
 
logging:
  level:
    com.self.sprintboot.learning.employee: DEBUG
    
eureka:         
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5    